# PHP CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-php/ for more details
#
version: 2
jobs:
  build:
    docker:
      # Specify the version you desire here
      - image: jakzal/phpqa:php7.4

      before_script:
        - composer install

      cache:
        paths:
          - vendor/
      # Specify service dependencies here if necessary
      # CircleCI maintains a library of pre-built images
      # documented at https://circleci.com/docs/2.0/circleci-images/
      # Using the RAM variation mitigates I/O contention
      # for database intensive operations.
      # - image: circleci/mysql:5.7-ram
      #
      # - image: redis:2.8.19

    steps:
      - SecurityChecker
      - CodingStandards
      - UnitTests

    security-checker:
      stage: SecurityChecker
      script:
        - local-php-security-checker  --path=./composer.lock
      allow_failure: false

    phpcs:
      stage: CodingStandards
      script:
        - phpcs -v --standard=PSR12 --ignore=./src/Kernel.php ./src
      allow_failure: false

    phpstan:
      stage: CodingStandards
      script:
        - phpstan analyse ./src
      allow_failure: false

    twig-lint:
      stage: CodingStandards
      script:
        - twig-lint lint ./templates
      allow_failure: false

    phpunit:
      stage: UnitTests
      script:
        - php bin/phpunit
      allow_failure: false